services:
  frontend:
    container_name: frontend
    build:
      context: ./edu-next/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - all

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - all

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - all

  backend:
    container_name: backend
    build:
      context: ./edu-backend/
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - OPENROUTER_API_KEY=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
      - SITE_URL=https://your-site-url.com
      - SITE_NAME=EduAssistant
    networks:
      - all
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  all:
    driver: bridge
